#!/bin/bash

#SCRIPTFILE="/home/duongtc/Data/Temp/myngle_items/AH-3509/check_bbb"
SCRIPTFILE="/data/autoscript/queueservices/mynglequeue.sh"
PIDFILE="/var/run/queueservices.pid"

case "$1" in
start)
   if [ -e $PIDFILE ]; then
      echo Queueservices is running, pid=`cat $PIDFILE`, please do stop or restart
      exit 1
   fi
   $SCRIPTFILE &
   echo $!>$PIDFILE
   $0 status
   ;;
stop)
   if [ -e $PIDFILE ]; then
      echo Stopping pid `cat $PIDFILE`
   else
      exit 0
   fi
   kill `cat $PIDFILE`
   rm $PIDFILE
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e $PIDFILE ]; then
      echo Queueservices is running, pid=`cat $PIDFILE`
   else
      echo Queueservices is NOT running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
